### ISSUE TITLE
Make this tidier

### ISSUE THREAD

**Issue by lampholder** [lampholder/termcast.me#1]
[exited]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/tom/bin/termcast.py", line 87, in stream
    ws.send(j)
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/websocket/_core.py", line 234, in send
    return self.send_frame(frame)
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/websocket/_core.py", line 259, in send_frame
    l = self._send(data)
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/websocket/_core.py", line 423, in _send
    return send(self.sock, data)
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/websocket/_socket.py", line 113, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
WebSocketConnectionClosedException: socket is already closed.

**Comment by lampholder** [comment]
I... think I fixed this.
